apiVersion: "v1"
kind: "BuildConfig"
metadata:
  name: "gradle-agent"
spec:
  runPolicy: "Serial"
  source:
    git:
      uri: "https://github.com/nofacer/agent-config.git"
  strategy:
    dockerStrategy:
      dockerfilePath: gradle/Dockerfile
  output:
    to:
      kind: "ImageStreamTag"
      name: "gradle-agent:latest"
